      - name: 👍 Start building the kernel (Sultan Mode)
        working-directory: vermeer-kernel
        run: |
          MAKE_ARGS=(
            O=out
            ARCH=arm64
            CC=clang
            LLVM=1
            LLVM_IAS=1
            CROSS_COMPILE=aarch64-linux-gnu-
            CROSS_COMPILE_COMPAT=arm-linux-gnueabihf-
          )
          
          echo "[*] Searching for the correct defconfig..."
          # Ищем конфиги vermeer, xaga или базовый mt6895. Берем первый найденный и обрезаем путь.
          ACTUAL_DEFCONFIG=$(find arch/arm64/configs -type f \( -name "*vermeer*defconfig" -o -name "*xaga*defconfig" -o -name "*mt6895*defconfig" \) | head -n 1 | sed 's|.*arch/arm64/configs/||')
          
          if [ -z "$ACTUAL_DEFCONFIG" ]; then
            echo "[!] Dynamic scan failed. Forcing default vendor/vermeer_defconfig"
            ACTUAL_DEFCONFIG="vendor/vermeer_defconfig"
          fi
          
          echo "[+] Target defconfig resolved to: $ACTUAL_DEFCONFIG"
          
          # Создаем конфиг с найденным именем
          make "${MAKE_ARGS[@]}" "$ACTUAL_DEFCONFIG"
          
          # СУЛТАНОВСКИЕ ОПТИМИЗАЦИИ (Вырезаем дебаг)
          ./scripts/config --file out/.config -d DEBUG_INFO -d GCOV_KERNEL -d KASAN -d KCSAN -d STACKTRACE
          ./scripts/config --file out/.config -e CONFIG_64BIT -e TCP_CONG_BBR -e CONFIG_KSU -e CONFIG_KSU_SUSFS
          
          make "${MAKE_ARGS[@]}" olddefconfig
          
          echo "[*] Kernel compilation..."
          make "${MAKE_ARGS[@]}" -j$(nproc)
